spring:
  application:
    name: demo_apps

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/nostra
    username: nostra
    password: welcome1
    hikari:
      connectionTimeout: 600000
      idleTimeout: 600000
      maxLifetime: 1800000
      maximumPoolSize: 10
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQL82Dialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB